name: MusicManager
on:
  push:
    paths: 
    - 'src/**'
    - '.github/workflows/**' 

jobs:
  build:
    name: 🛠️ Build and test
    runs-on: windows-2025
    
    steps:
    - name: 🔖 Check-out
      uses: actions/checkout@v6

    - name: ⚙️ Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10'
    
    - name: ⚙️ Setup MSBuild
      uses: microsoft/setup-msbuild@v3
    
    - name: 🛠️ Build
      run: msbuild ./src/MusicManager/MusicManager.slnx /restore /p:Configuration=Release /p:GenerateAppxPackageOnBuild=false
    
    - name: 🕵️ Test
      run: |
        echo "## 🕵️ Test Results" >> $Env:GITHUB_STEP_SUMMARY
        cd ./src/MusicManager
        dotnet test --solution ./MusicManager.slnf --coverage        
